### ISSUE TITLE
Desktop sync doesn't work

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/trilium_ynh#4]
Hi there

I've started working on a package for this app a few days ago, probably just before you did... So I did start from scratch...

Anyway, if it can help, I've a fully working package over there https://github.com/maniackcrudelis/trilium_ynh.

I've one issue though, and I'm interested to know if you managed to fix it yet. When synchronizing from a desktop client it fails when using the domain name but works with the IP and port. Looks like there's an issue around the nginx configuration.

If you manage to fix that issue, I'm interested to know how you did ;)

**Comment by Jules-Bertholet** [comment]
I never tested desktop sync, no clue if it works or not.

**Comment by maniackcrudelis** [comment]
Just to give you a heads up, the synchronization doesn't work for Trilium because of the SSO cookie, found the issue with the dev of Trilium. [Failling to sync from desktop to a server #1822](https://github.com/zadam/trilium/issues/1822#issuecomment-814428783)

And I opened an [issue about it on YunoHost repo](https://github.com/YunoHost/issues/issues/1768).

**Comment by Jules-Bertholet** [comment]
Good job on debugging this! If you find a way to fix the issue from within the app feel free to make a PR.

**Comment by maniackcrudelis** [comment]
The issue is fixed by the PR https://github.com/YunoHost/SSOwat/pull/182, no more cookie from YunoHost during the synchronization, it does work now.
Nothing to do in nginx config to fix it, just to wait for the fix into a future release.
