### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by guneydoganer** [YunoHost-Apps/trilium_ynh#5]
### Describe the bug

*I just tried to install Trilium using the Webadmin, but the installation failed.*

### Context

- Hardware: *VPS bought online through Upcloud (their $5 package with 1 vCPU and 1GB RAM)*
- YunoHost version: YunoHost 4.1.8 (stable)
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- Search for the Trilium app on the webclient and select it. 
- Disable access to anonymous users.
- Select custom domainname.
- Remove everything after the trailing slash / (so basically install at root directory).
- Install

### Logs

https://paste.yunohost.org/raw/qenepukoci

**Comment by Jules-Bertholet** [comment]
```
2021-04-14 21:20:49,829: DEBUG - error An unexpected error occurred: "/opt/yunohost/trilium/node_modules/electron: spawn ENOMEM"
```

It seems you ran out of memory during a build step. Try adding swap space and installing again

**Comment by Jules-Bertholet** [comment]
With #7 the package will no longer try to build electron, reducing memory requirements
