### ISSUE TITLE
Installation completed, service does not start, error 502

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/trilium_ynh#8]
### Describe the bug

Installation completed, but the trillum service does not start and shows error 502

Maybe this is the relevant part of the log:

```
Apr 25 15:24:31 node[32002]: Error: The module '/opt/yunohost/trilium/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
Apr 25 15:24:31 node[32002]: was compiled against a different Node.js version using
Apr 25 15:24:31 node[32002]: NODE_MODULE_VERSION 83. This version of Node.js requires
Apr 25 15:24:31 node[32002]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
```

See here: https://paste.yunohost.org/anasafugel

### Context

- Hardware: *VPS bought online ...*
- YunoHost version: 4.1.8
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
 

### Steps to reproduce

- Install trilium via webadmin

**Comment by Jules-Bertholet** [comment]
Testing PR: https://github.com/YunoHost-Apps/trilium_ynh/pull/7

**Comment by Jules-Bertholet** [comment]
Fixed
